src/core/urls.py
from django.urls import path 
from .views import Homepage 

app_name="core"

urlpatterns = [
    path("" ,Homepage.as_view(),name="homepage"),
]

src/myauth/urls.py
from django.urls import path
from . import views 

app_name="auth"

urlpatterns = [
    path("login/", views.login, name="login"),
]

src/topics/urls.py
from django.urls import path 
from . import views

app_name="topics"

urlpatterns = [
    path("<uuid:pk>/" ,views.TopicDetailView.as_view() ,name="topic_detail")
]

src/vulnerableweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("topics/", include("topics.urls", namespace="topics")),
    path("auth/", include("myauth.urls", namespace="auth")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/core/models.py
from django.db import models

# Create your models here.

class TimeStamp(models.Model):
    """
        A base Model with creation and update 
        time to get inherited by other models 
    """
    created=models.DateTimeField(auto_now_add=True ,verbose_name="تاریخ ایجاد")
    updated=models.DateTimeField(auto_now=True ,verbose_name="آخرین بروزرسانی")

    class Meta:
        abstract = True 

src/exercise/models.py
from ckeditor.fields import RichTextField

from django.db import models
from django.shortcuts import reverse

from core.models import TimeStamp
from topics.models import Topic
# Create your models here.


class Exercise(TimeStamp):

    title = models.CharField(max_length=200, verbose_name="موضوع")
    instruction = RichTextField(verbose_name="راهنما", blank=True)
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, verbose_name="مبحث")
    URL = models.CharField(max_length=200)

    class Meta:
        ordering = ("created", "updated")
        verbose_name = "تمرین"
        verbose_name_plural = "تمارین"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('exercise:exercise', args=[str(self.uuid)])


class ExerciseTip(models.Model):

    exercise = models.ForeignKey(Exercise, models.CASCADE, related_name="tips")
    tip = models.TextField()

    class Meta:
        ordering = ("exercise",)
        verbose_name = "راهنمایی"
        verbose_name_plural = "راهنمایی ها"

    def __str__(self):
        return self.tip

src/topics/models.py
import os

from ckeditor.fields import RichTextField
import uuid
from django.shortcuts import reverse
from django.db import models

from core.models import TimeStamp
# Create your models here.


def topic_image_upload_path(instance, filename):
    # Generate a unique filename using UUID and creation date
    topic_uuid = uuid.uuid4()
    ext = filename.split('.')[-1]
    filename = f'{topic_uuid}.{ext}'

    # Return the full file path
    return os.path.join('topic_images', filename)


class Topic(TimeStamp):

    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200, verbose_name="موضوع")
    text = RichTextField(verbose_name="متن")
    pic = models.ImageField(verbose_name="تصویر",
                            upload_to=topic_image_upload_path,
                            null=True
                            )

    class Meta:
        ordering = ("created", "updated")
        verbose_name = "مبحث"
        verbose_name_plural = "مباحث"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('topics:topic_detail', args=[str(self.uuid)])

src/myauth/forms.py
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(label="نام کاربری", widget=forms.TextInput(
        attrs={"class": "LoginPageField"}))
    password = forms.CharField(label="رمز عبور", widget=forms.PasswordInput(
        attrs={"class": "LoginPageField"}))

src/core/views.py
from django.shortcuts import render
from django.views.generic import ListView
from topics.models import Topic
# Create your views here.


class Homepage(ListView):
    model=Topic
    template_name="core/homepage.html"
    context_object_name="topics"

src/exercise/views.py
from django.shortcuts import render

# Create your views here.

src/myauth/views.py
from django.contrib.auth.hashers import make_password
from django.db import connection
from django.contrib.auth import get_user_model ,login as auth_login
from django.shortcuts import redirect, render
from django.contrib import messages 

from .forms import UserLoginForm

def login(request):
    """
        topic 1 : sqli             
        Intentional vulnerability (DO NOT USE IN REAL WORLD CODE)
    """
    if(request.method=="POST"):
        form=UserLoginForm(data=request.POST)
        if(form.is_valid()):
            cd=form.cleaned_data
            username=cd["username"]
            password=make_password(cd['password'])
            query = "SELECT * FROM auth_user WHERE username='" + username + "' AND password='" + password + "'"
            with connection.cursor() as cursor:
                cursor.execute(query)
                result=cursor.fetchone()
            if(result):
                user=get_user_model().objects.get(id=result[0])
                if(user.is_active):
                    auth_login(request, user)
                    return(redirect('/'))
                else:
                    messages.error(request,"حساب کاربری شما غیر فعال است.لطفا به ایمیل خود رفته با ایمیل ارسال شده حساب خود را فعال کنید.")
            else:
                messages.error(request,"نام کاربری یا رمز عبور وارد شده صحیح نمی باشد.")
    return(render(request,"auth/login.html")) 

src/topics/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from topics.models import Topic
# Create your views here.


class TopicDetailView(DetailView):
    model=Topic
    template_name="topics/topic_detail.html"

src/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html  dir="rtl" lang="fa">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <meta name="author" charset="ahmadihamed231@gmailcom">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script> 
        <link rel="stylesheet" href="{%  static 'core/css/base.css' %}" >

        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

        <title>{%block page_title%}{% endblock page_title %}</title>
        {% block head %}
        {% endblock head %}
    </head>
    <body class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-lg navbar-custom navbar-white ">
            <a class="navbar-brand" href="{% url 'core:homepage' %}">vulernableweb</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <img src="{% static 'core/images/icon-menu.png' %}">
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="">پروفایل</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">خروج</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="">ورود</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">ثبت نام</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </nav>
          <section class="pt-1 pb-1">
            {% block content %}
            {% endblock content %}
          </section>
          {% include 'core/footer.html' %}
    </body>
</html>

src/core/templates/core/footer.html
<section class="text-center text-white mt-auto" id="base_footer">
    vulernableweb 2023  
</section>

src/core/templates/core/homepage.html
{% extends "core/base.html" %}
{% load static %}
{% load custome_filters %}
{% block head %}
    <link rel="stylesheet" href="{% static 'core/css/homepage.css' %}">
{% endblock head %}
{% block page_title %}
homepage
{% endblock page_title %}
{% block content %}
<div id="topics_section" class="container mt-2 row m-auto text-center">
    {% for topic in topics %}
    <div class="col-xs-8 col-sm-6 col-md-6 col-lg-4 topics">
        <a href="{{topic.get_absolute_url}}" class="text-dark text-decoration-none ">
            {% if topic.pic %}
                <img src="{{topic.pic.url}}" class="topic_image img-fluid " >
            {% endif %}
            <p class="text-center">{{ topic.text|striphtml|truncatewords:10 }}</p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

src/topics/templates/topics/topic_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet"  href="{% static 'topics/css/topic_detail.css' %}">
{% endblock head %}
{% block content %}
<div class="topic-container container" >
    <section class="row">
    <h2 id="topic-title" class="col-md-8">{{topic.title}}</h2>
    {% if topic.pic %}
        <section class="topic_image">
            <img src="{{topic.pic.url}}" > 
        </section>
    {% endif %}
    </section>

    <div id="topic-text">{{topic.text|safe}}</div>
</div>
{% endblock content %}